const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={jobs:[],orgs:[],currentJob:null,currentWorkspace:null,existingImport:null,updateRun:null,bulkBatch:null};
const titles={dashboard:['PORTFOLIO INTELLIGENCE','Tableau de bord','Créer → Diagnostiquer → Actualiser → Gouverner.'],jobs:['STRUCTURED JOB DATA','Fiches de poste','Structurer, comparer, versionner et gouverner les rôles.'],newjob:['ADAPTIVE JOB INTAKE','Créer une fiche','Comprendre le rôle avant de rédiger.'],workspace:['JOB WORKSPACE','Fiche structurée','AI assists. Experts govern.'],update:['UPDATE INTELLIGENCE','Importer & actualiser','Avant / Après / Pourquoi — sans écraser le contenu client.'],research:['RESEARCH & BENCHMARK','Research Workspace','Des preuves avant la rédaction.'],architecture:['JOB ARCHITECTURE','Architecture & Skills','Familles, niveaux, skills et passerelles.'],bulk:['PORTFOLIO INTELLIGENCE','Bulk Job Audit','Détecter obsolescence, doublons, overlaps et gaps.'],validation:['HUMAN GOVERNANCE','Centre de validation','Les décisions humaines restent l’autorité finale.'],documents:['DOCUMENT INTELLIGENCE','Documents & Knowledge','Transformer le corpus client en contexte exploitable.'],output:['OUTPUT BLUEPRINT','Livrable final','La structure de sortie s’adapte au client.'],connectors:['GOVERNED AI','IA & Connecteurs','Intelligence multi-source, traçable et contrôlée.']};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function api(path,opt={}){const r=await fetch('/api/v1'+path,{headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})},...opt});if(!r.ok){let x;try{x=await r.json()}catch{x={detail:r.statusText}};throw new Error(x.detail||x.error||r.statusText)}const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function showView(v){$$('.view').forEach(x=>x.classList.add('hidden'));const el=$('#'+v+'View');if(el)el.classList.remove('hidden');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const t=titles[v]||titles.dashboard;$('#pageEyebrow').textContent=t[0];$('#pageTitle').textContent=t[1];$('#pageSub').textContent=t[2];$('#sidebar').classList.remove('open');scrollTo(0,0);if(v==='validation')loadValidations();if(v==='documents')loadDocuments();if(v==='connectors')loadConnectors();if(v==='jobs')renderJobs();}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#mobileMenuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function statusChip(s){let c='';if(['approved','published'].includes(s))c='green';else if(['manager_validation','hr_review','interview'].includes(s))c='amber';else if(['changes_requested','rejected'].includes(s))c='red';return `<span class="chip ${c}">${s.replaceAll('_',' ')}</span>`}
function scoreChip(n){const c=n>=85?'green':n>=70?'amber':'red';return `<span class="chip ${c}">${Math.round(n)}</span>`}
async function boot(){try{state.orgs=await api('/organizations');state.jobs=await api('/jobs');renderOrgSelects();renderDashboard();renderJobs();renderJobSelects();renderOutputSections();const st=await api('/ai/status');$('#sideProvider').textContent=st.selected_provider==='openai'?'OpenAI · live':'Teamwork Expert Engine · pilot';}catch(e){toast('Erreur de chargement : '+e.message)}}
function renderOrgSelects(){['njOrg'].forEach(id=>{const el=$('#'+id);if(el)el.innerHTML=state.orgs.map(o=>`<option value="${o.id}">${o.legal_name}</option>`).join('')})}
function renderDashboard(){const j=state.jobs;$('#mActive').textContent=j.length;$('#mQuality').textContent=Math.round(j.reduce((a,x)=>a+(x.quality_score||0),0)/(j.length||1));$('#mFresh').textContent=Math.round(j.reduce((a,x)=>a+(x.freshness_score||0),0)/(j.length||1));$('#mValidation').textContent=j.filter(x=>['manager_validation','hr_review'].includes(x.workflow_status)).length;$('#dashboardJobs').innerHTML=j.slice(0,5).map(x=>`<tr><td><b>${x.title_fr}</b><br><small>${x.reports_to||''}</small></td><td>${x.department||'—'}</td><td>${scoreChip(x.quality_score)}</td><td>${scoreChip(x.freshness_score)}</td><td>${statusChip(x.workflow_status)}</td><td><button class="mini" onclick="openJob('${x.id}')">Ouvrir</button></td></tr>`).join('')}
function renderJobs(){const q=($('#jobSearch')?.value||'').toLowerCase(),s=$('#jobStatus')?.value||'';const rows=state.jobs.filter(x=>(!q||(x.title_fr+' '+x.department).toLowerCase().includes(q))&&(!s||x.workflow_status===s));$('#jobGrid').innerHTML=rows.map(x=>`<article class="job-card" onclick="openJob('${x.id}')"><span class="kicker">${x.department||'JOB ROLE'}</span><h3>${x.title_fr}</h3><p>${x.reports_to||'Rattachement à cadrer'} · ${x.location||'—'}</p><div class="row"><div>${statusChip(x.workflow_status)}</div><div><span class="score-sm">${Math.round(x.quality_score||0)}</span><small>/100</small></div></div></article>`).join('')||'<div class="empty">Aucun poste ne correspond aux filtres.</div>'}
$('#jobSearch').oninput=renderJobs;$('#jobStatus').onchange=renderJobs;
function renderJobSelects(){['researchJob','outputJob'].forEach(id=>{const el=$('#'+id);if(el)el.innerHTML=state.jobs.map(x=>`<option value="${x.id}">${x.title_fr}</option>`).join('')})}
async function createJob(){try{const payload={organization_id:$('#njOrg').value,title_fr:$('#njTitle').value,title_en:$('#njTitleEn').value,department:$('#njDept').value,reports_to:$('#njReports').value,location:$('#njLocation').value,direct_reports:+$('#njReportsCount').value||0};const j=await api('/jobs',{method:'POST',body:JSON.stringify(payload)});state.jobs.unshift(j);state.currentJob=j.id;renderDashboard();renderJobs();renderJobSelects();const iv=await api(`/jobs/${j.id}/interview/start?locale=fr`,{method:'POST'});showInterview(iv);toast('Poste créé — entretien adaptatif lancé');}catch(e){toast(e.message)}}
function showInterview(iv){$('#interviewPanel').classList.remove('hidden');$('#interviewQuestion').textContent=iv.question.text;$('#interviewWhy').textContent=iv.question.why;$('#interviewProgress').textContent=Math.round((iv.progress||.2)*100)+'%';$('#interviewOptions').innerHTML=iv.question.options.map(o=>`<button onclick="answerInterview(this.textContent)">${o}</button>`).join('');$('#interviewPanel').scrollIntoView({behavior:'smooth'})}
async function answerInterview(answer){try{await api(`/jobs/${state.currentJob}/interview/answer`,{method:'POST',body:JSON.stringify({key:'decision_authority',answer})});toast('Contexte capturé — lancement Research + Analyse');await analyzeCurrent();}catch(e){toast(e.message)}}
async function openJob(id){state.currentJob=id;showView('workspace');try{state.currentWorkspace=await api(`/jobs/${id}/workspace`);renderWorkspace()}catch(e){toast(e.message)}}
async function analyzeCurrent(){if(!state.currentJob){state.currentJob=$('#researchJob')?.value||state.jobs[0]?.id}if(!state.currentJob)return;showView('workspace');$('#wsFinality').textContent='Research & Benchmark en cours…';try{state.currentWorkspace=await api(`/jobs/${state.currentJob}/analyze`,{method:'POST'});renderWorkspace();state.jobs=await api('/jobs');renderDashboard();renderJobs();renderJobSelects();toast('Analyse terminée — recommandations prêtes')}catch(e){toast(e.message)}}
function renderWorkspace(){const w=state.currentWorkspace;if(!w)return;const j=w.job;$('#wsTitle').textContent=j.title_fr;$('#wsMeta').textContent=`${j.department||'—'} · ${j.reports_to||'—'} · ${j.location||'—'} · version ${j.version||'—'}`;$('#wsQuality').textContent=Math.round(j.quality_score||0);$('#wsFresh').textContent=Math.round(j.freshness_score||0);$('#wsFinality').textContent=w.profile.finality_fr||'À cadrer';$('#wsMissionCount').textContent=(w.missions||[]).length+' missions';$('#wsMissions').innerHTML=(w.missions||[]).map((m,i)=>`<div class="mission"><b>${i+1}. ${m.label}</b>${(m.activities||[]).length?`<ul>${m.activities.map(a=>`<li>${a}</li>`).join('')}</ul>`:''}</div>`).join('');$('#wsResponsibilities').innerHTML=(w.responsibilities||[]).map(r=>`<div class="responsibility"><b>${r.label}</b><small>Autorité : ${r.authority||'à valider'}</small></div>`).join('');$('#wsSkills').innerHTML=(w.skills||[]).map(s=>`<span class="skill">${s.label} <b>${s.level||''}</b></span>`).join('');$('#wsKpis').innerHTML=(w.kpis||[]).map(k=>`<div class="kpi-row"><b>${k.label}</b><span class="chip">${k.target||'à cadrer'}</span></div>`).join('')||'<div class="empty">Aucun KPI validé — la rubrique peut rester masquée dans le livrable.</div>';$('#wsSources').innerHTML=(w.sources||[]).slice(0,7).map(s=>`<span class="chip ${s.type==='teamwork'?'violet':s.type==='company_document'?'green':'blue'}">${s.title}</span>`).join('');const qb=w.quality_breakdown||{};$('#qualityBreakdown').innerHTML=Object.entries(qb).map(([k,v])=>`<div class="quality-line"><div><label>${k} <b>${v}</b></label><i style="width:${Math.min(100,v*6.7)}%"></i></div><span>${v}</span></div>`).join('');$('#wsRecs').innerHTML=(w.recommendations||[]).map(r=>`<div class="recommendation"><b>${r.title}</b><p>${r.why}</p></div>`).join('')}
function editFinality(){const cur=$('#wsFinality').textContent;const v=prompt('Modifier la finalité',cur);if(!v)return;api(`/editor/jobs/${state.currentJob}/finality`,{method:'PATCH',body:JSON.stringify({value:v})}).then(()=>{state.currentWorkspace.profile.finality_fr=v;renderWorkspace();toast('Finalité mise à jour')}).catch(e=>toast(e.message))}
async function submitValidation(){if(!state.currentJob)return;try{await api(`/jobs/${state.currentJob}/submit-validation`,{method:'POST'});toast('Envoyé au manager pour validation');state.jobs=await api('/jobs');renderDashboard();showView('validation')}catch(e){toast(e.message)}}
async function importExisting(){const f=$('#existingFile').files[0];if(!f){toast('Choisis une fiche à importer');return}const fd=new FormData();fd.append('file',f);fd.append('organization_id',state.orgs[0]?.id||'org-atlas');fd.append('mode',$('#updateMode').value);try{const imp=await api('/existing-jobs/import',{method:'POST',body:fd});state.existingImport=imp;$('#existingStatus').innerHTML='<div class="callout"><b>Document analysé</b><span>'+imp.filename+'</span></div>';$('#existingExtract').innerHTML=`<div class="existing-result"><div><span>Intitulé</span><b>${imp.extracted.title}</b></div><div><span>Finalité</span><b>Détectée</b></div><div><span>Missions</span><b>${imp.extracted.missions}</b></div><div><span>Skills</span><b>${imp.extracted.skills}</b></div><div><span>KPI</span><b>${imp.extracted.kpis}</b></div><div><span>Mode</span><b>${imp.mode}</b></div></div><button class="btn primary full" style="margin-top:10px" onclick="generateUpdate()">2. Générer l’actualisation</button>`;state.jobs=await api('/jobs');renderDashboard();renderJobs();renderJobSelects();toast('Import structuré — aucune donnée manquante inventée')}catch(e){toast(e.message)}}
async function generateUpdate(){try{const r=await api(`/existing-jobs/imports/${state.existingImport.id}/update-intelligence`,{method:'POST'});state.updateRun=r;renderUpdates();$('#updatePanel').classList.remove('hidden');$('#updatePanel').scrollIntoView({behavior:'smooth'});toast('Update Intelligence terminé')}catch(e){toast(e.message)}}
function renderUpdates(){const r=state.updateRun;if(!r)return;$('#updateItems').innerHTML=r.items.map(x=>`<div class="update-item" data-id="${x.id}"><div class="panel-head"><div><span class="kicker">${x.section} · ${x.action}</span><span class="chip ${x.confidence>=.88?'green':'amber'}">Confiance ${Math.round(x.confidence*100)}%</span></div><span class="chip ${x.decision==='accepted'?'green':x.decision==='rejected'?'red':''}">${x.decision}</span></div><div class="diff"><div class="diff-box"><small>AVANT</small><p>${x.before||'—'}</p></div><div class="diff-box after"><small>APRÈS</small><p>${x.after}</p></div></div><div class="why-box"><b>Pourquoi ?</b> ${x.why}</div><div class="decision-row"><button class="mini" onclick="decideUpdate('${x.id}','accepted')">✓ Accepter</button><button class="mini" onclick="decideUpdate('${x.id}','rejected')">× Refuser</button></div></div>`).join('')}
async function decideUpdate(id,decision){try{await api(`/existing-jobs/update-runs/${state.updateRun.id}/items/${id}`,{method:'PATCH',body:JSON.stringify({decision})});const x=state.updateRun.items.find(i=>i.id===id);if(x)x.decision=decision;renderUpdates()}catch(e){toast(e.message)}}
async function acceptAllUpdates(){try{state.updateRun=await api(`/existing-jobs/update-runs/${state.updateRun.id}/accept-all`,{method:'POST'});renderUpdates();toast('Toutes les propositions sont acceptées — pas encore appliquées')}catch(e){toast(e.message)}}
async function applyUpdates(){try{const r=await api(`/existing-jobs/update-runs/${state.updateRun.id}/apply`,{method:'POST'});toast('Nouvelle version '+r.version+' créée — baseline conservée');state.jobs=await api('/jobs');renderDashboard();renderJobs();renderJobSelects();await openJob(r.job.id)}catch(e){toast(e.message)}}
async function runResearch(){const id=$('#researchJob').value,q=$('#researchQuery').value;$('#researchSummary').innerHTML='<div class="empty">Research Engine en cours…</div>';try{const r=await api(`/research/jobs/${id}/run`,{method:'POST',body:JSON.stringify({query:q})});$('#researchSummary').innerHTML=`<div class="metrics" style="grid-template-columns:1fr 1fr;margin:0 0 10px"><article><span>Sources</span><strong>${r.source_count}</strong><em>traçables</em></article><article><span>Confiance</span><strong>${Math.round((r.confidence||0)*100)}%</strong><em>fusion</em></article></div><p>${r.summary}</p><div class="chips" style="margin-top:10px">${(r.convergence||[]).map(x=>`<span class="chip green">${x}</span>`).join('')}</div>`;$('#sourceCount').textContent=r.source_count+' sources';$('#evidenceList').innerHTML=(r.evidence||[]).map(e=>`<div class="evidence"><div><b>${e.title||'Source'}</b><p>${e.type||e.provenance||'evidence'} · ${e.provenance||'traceable'}</p></div><span class="chip">Autorité ${Math.round((e.authority||.75)*100)}</span><span class="confidence">${Math.round((e.confidence||.8)*100)}%</span></div>`).join('');toast('Benchmark terminé')}catch(e){$('#researchSummary').innerHTML='<div class="empty">'+e.message+'</div>';toast(e.message)}}
async function runBulk(){const f=$('#bulkFile').files[0];if(!f){toast('Sélectionne un CSV');return}const fd=new FormData();fd.append('file',f);try{const imp=await api('/bulk-audit/imports',{method:'POST',body:fd});state.bulkBatch=imp.batch_id;await api(`/bulk-audit/imports/${imp.batch_id}/analyze`,{method:'POST'});const d=await api(`/bulk-audit/imports/${imp.batch_id}/dashboard`);$('#bulkStatus').innerHTML=`<div class="callout"><b>${imp.row_count} rôles importés</b><span>Audit terminé</span></div>`;const m=d.metrics;$('#bulkResults').innerHTML=`<div class="bulk-metrics"><div><span>Jobs</span><b>${m.jobs}</b></div><div><span>Quality</span><b>${m.quality_avg}</b></div><div><span>Freshness</span><b>${m.freshness_avg}</b></div><div><span>Doublons</span><b>${m.duplicates}</b></div><div><span>KPI manquants</span><b>${m.missing_kpis}</b></div><div><span>Skills gaps</span><b>${m.skills_gaps}</b></div></div><article class="panel" style="margin-top:12px"><span class="kicker">FINDINGS</span>${d.findings.map(x=>`<div class="finding"><b>${x.title}</b><span class="chip ${x.severity==='high'?'red':'amber'}">${x.type}</span></div>`).join('')}</article>`;toast('Bulk Audit terminé')}catch(e){toast(e.message)}}
async function loadValidations(){try{const v=await api('/validations');$('#validationList').innerHTML=v.length?v.map(x=>`<div class="validation-card"><div><span class="kicker">${x.status}</span><h3>${x.job_title}</h3><p>Demandé par ${x.requested_by||'RH'} · La version approuvée reste immuable.</p></div><div class="validation-actions">${x.status==='pending'?`<button class="btn primary" onclick="validationAction('${x.id}','approve')">Approuver</button><button class="btn ghost" onclick="validationAction('${x.id}','request-changes')">Modifications</button><button class="btn danger" onclick="validationAction('${x.id}','reject')">Rejeter</button>`:statusChip(x.status)}</div></div>`).join(''):'<div class="panel empty">Aucune demande de validation en attente.</div>'}catch(e){toast(e.message)}}
async function validationAction(id,act){try{await api(`/validations/${id}/${act}`,{method:'POST',body:JSON.stringify({comment:act==='request-changes'?'Préciser le périmètre de décision.':''})});toast('Décision enregistrée');state.jobs=await api('/jobs');renderDashboard();loadValidations()}catch(e){toast(e.message)}}
async function uploadDocument(){const f=$('#docFile').files[0];if(!f){toast('Choisis un document');return}const fd=new FormData();fd.append('file',f);fd.append('role',$('#docRole').value);try{const d=await api('/documents',{method:'POST',body:fd});$('#docStatus').innerHTML=`<div class="callout"><b>${d.filename}</b><span>${d.chars} caractères extraits · ${d.status}</span></div>`;toast('Document analysé');loadDocuments()}catch(e){toast(e.message)}}
async function loadDocuments(){try{const d=await api('/documents');$('#docList').innerHTML=d.length?d.map(x=>`<div class="doc-card"><div><b>${x.filename}</b><span>${x.role} · ${x.chars} caractères</span></div><span class="chip green">${x.status}</span></div>`).join(''):'<div class="empty">Aucun document importé dans cette session.</div>'}catch(e){toast(e.message)}}
async function searchDocuments(){const q=$('#docSearch').value;if(!q)return;try{const r=await api('/documents/search/knowledge?q='+encodeURIComponent(q));$('#docSearchResults').innerHTML=r.length?r.map(x=>`<div class="recommendation"><b>${x.filename}</b><p>${x.excerpt}</p></div>`).join(''):'<div class="empty">Aucun passage trouvé.</div>'}catch(e){toast(e.message)}}
const sectionNames=['Identification du poste','Finalité','Positionnement','Missions','Activités','Responsabilités','Autonomie','Relations internes / externes','Compétences','Formation & expérience','KPI','Conditions d’exercice','Certifications'];
function renderOutputSections(){$('#outputSections').innerHTML=sectionNames.map((x,i)=>`<div class="output-row"><input type="checkbox" ${[0,1,3,5,8].includes(i)?'checked':''}><span>${x}</span><select><option ${[0,1,3,5].includes(i)?'selected':''}>Obligatoire</option><option ${[6,7,8,9,10].includes(i)?'selected':''}>Conditionnel</option><option>Optionnel</option><option ${[11,12].includes(i)?'selected':''}>Masqué</option></select></div>`).join('')}
function downloadExport(fmt){const id=$('#outputJob').value||state.jobs[0]?.id;if(!id){toast('Aucun poste');return}location.href=`/api/v1/exports/jobs/${id}.${fmt}?locale=fr&mode=official`}
async function loadConnectors(){try{const [c,l]=await Promise.all([api('/connectors'),api('/live-intelligence/status')]);$('#connectorGrid').innerHTML=c.connectors.map(x=>`<article class="connector-card"><span class="kicker">${x.category}</span><h3>${x.label}</h3><p>${x.description_fr||''}</p><div class="status"><span class="chip ${x.status==='ready'?'green':'amber'}">${x.status}</span><button class="mini" onclick="testConnector('${x.provider}')">Tester</button></div></article>`).join('');const entries=[['OpenAI',l.openai.configured,l.openai.model],['OpenAI Web Search',l.openai.web_search_ready,l.openai.web_search_ready?'ready':'clé requise'],['ESCO',l.esco.ready,l.esco.selected_version],['ROME 4.0',l.rome.ready,'accès développeur requis'],['O*NET',l.onet.ready,'API key'],['Google Web',l.google.ready,'partner access']];$('#liveStatus').innerHTML=entries.map(x=>`<div class="live-line"><b>${x[0]}</b><span>${x[2]||''}</span><span class="chip ${x[1]?'green':'amber'}">${x[1]?'ready':'not configured'}</span></div>`).join('')}catch(e){toast(e.message)}}
async function testConnector(p){try{const r=await api(`/connectors/${p}/test`,{method:'POST'});toast(`${p} : ${r.status}`)}catch(e){toast(e.message)}}
boot();
